export const ERROR_KEYS = {
  // 注册相关
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
  INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
  INVALID_USERNAME_FORMAT: "INVALID_USERNAME_FORMAT",
  INVALID_PASSWORD_FORMAT: "INVALID_PASSWORD_FORMAT",
  PASSWORDS_DO_NOT_MATCH: "PASSWORDS_DO_NOT_MATCH",
  VERIFICATION_CODE_EXPIRED: "VERIFICATION_CODE_EXPIRED",
  INVALID_VERIFICATION_CODE: "INVALID_VERIFICATION_CODE",
  REGISTRATION_FAILED: "REGISTRATION_FAILED",

  // 登录相关
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_NOT_ACTIVATED: "ACCOUNT_NOT_ACTIVATED",
  LOGIN_FAILED: "LOGIN_FAILED",

  // 密码重置相关
  PASSWORD_RESET_TOKEN_EXPIRED: "PASSWORD_RESET_TOKEN_EXPIRED",
  INVALID_PASSWORD_RESET_TOKEN: "INVALID_PASSWORD_RESET_TOKEN",
  PASSWORD_RESET_FAILED: "PASSWORD_RESET_FAILED",

  // 邮箱验证相关
  EMAIL_VERIFICATION_FAILED: "EMAIL_VERIFICATION_FAILED",
  EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",

  // 权限相关
  UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",

  // 令牌相关
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  // 输入验证相关
  REQUIRED_FIELD_MISSING: "REQUIRED_FIELD_MISSING",
  INVALID_INPUT_FORMAT: "INVALID_INPUT_FORMAT",

  // 网络相关
  NETWORK_ERROR: "NETWORK_ERROR",
  REQUEST_TIMEOUT: "REQUEST_TIMEOUT",

  // 通用错误
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",

  LOGOUT_FAILED: "LOGOUT_FAILED",
};

export const SUCCESS_KEYS = {
  // 注册相关
  REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
  VERIFICATION_CODE_SENT: "VERIFICATION_CODE_SENT",
  COMPLETE_REGISTRATION: "COMPLETE_REGISTRATION",
  REGISTERING: "REGISTERING",

  // 登录相关
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  // 密码重置相关
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
  PASSWORD_RESET_EMAIL_SENT: "PASSWORD_RESET_EMAIL_SENT",

  // 邮箱验证相关
  EMAIL_VERIFICATION_SUCCESS: "EMAIL_VERIFICATION_SUCCESS",

  // 个人信息相关
  PROFILE_UPDATE_SUCCESS: "PROFILE_UPDATE_SUCCESS",

  // 通用成功
  OPERATION_SUCCESS: "OPERATION_SUCCESS",

  // 登出相关
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};

export const getErrorMessage = (errorKey) => {
  const errorMessages = {
    // 注册相关
    [ERROR_KEYS.EMAIL_ALREADY_EXISTS]: "该邮箱已被注册",
    [ERROR_KEYS.USERNAME_ALREADY_EXISTS]: "该用户名已被使用",
    [ERROR_KEYS.INVALID_EMAIL_FORMAT]: "无效的邮箱格式",
    [ERROR_KEYS.INVALID_USERNAME_FORMAT]: "无效的用户名格式",
    [ERROR_KEYS.INVALID_PASSWORD_FORMAT]: "无效的密码格式",
    [ERROR_KEYS.PASSWORDS_DO_NOT_MATCH]: "两次输入的密码不匹配",
    [ERROR_KEYS.VERIFICATION_CODE_EXPIRED]: "验证码已过期",
    [ERROR_KEYS.INVALID_VERIFICATION_CODE]: "无效的验证码",
    [ERROR_KEYS.REGISTRATION_FAILED]: "注册失败",

    // 登录相关
    [ERROR_KEYS.USER_NOT_FOUND]: "用户不存在",
    [ERROR_KEYS.INCORRECT_PASSWORD]: "密码错误",
    [ERROR_KEYS.ACCOUNT_LOCKED]: "账户已被锁定",
    [ERROR_KEYS.ACCOUNT_NOT_ACTIVATED]: "账户未激活",
    [ERROR_KEYS.LOGIN_FAILED]: "登录失败",

    // 密码重置相关
    [ERROR_KEYS.PASSWORD_RESET_TOKEN_EXPIRED]: "密码重置令牌已过期",
    [ERROR_KEYS.INVALID_PASSWORD_RESET_TOKEN]: "无效的密码重置令牌",
    [ERROR_KEYS.PASSWORD_RESET_FAILED]: "密码重置失败",

    // 邮箱验证相关
    [ERROR_KEYS.EMAIL_VERIFICATION_FAILED]: "邮箱验证失败",
    [ERROR_KEYS.EMAIL_ALREADY_VERIFIED]: "邮箱已经验证过",

    // 权限相关
    [ERROR_KEYS.UNAUTHORIZED_ACCESS]: "未授权访问",
    [ERROR_KEYS.INSUFFICIENT_PERMISSIONS]: "权限不足",

    // 令牌相关
    [ERROR_KEYS.INVALID_TOKEN]: "无效的令牌",
    [ERROR_KEYS.TOKEN_EXPIRED]: "令牌已过期",

    // 输入验证相关
    [ERROR_KEYS.REQUIRED_FIELD_MISSING]: "缺少必填字段",
    [ERROR_KEYS.INVALID_INPUT_FORMAT]: "输入格式无效",

    // 网络相关
    [ERROR_KEYS.NETWORK_ERROR]: "网络错误",
    [ERROR_KEYS.REQUEST_TIMEOUT]: "请求超时",

    // 通用错误
    [ERROR_KEYS.INTERNAL_SERVER_ERROR]: "服务器内部错误",
    [ERROR_KEYS.SERVICE_UNAVAILABLE]: "服务不可用",
    [ERROR_KEYS.UNKNOWN_ERROR]: "未知错误",
    [ERROR_KEYS.LOGOUT_FAILED]: "登出失败",
  };

  return errorMessages[errorKey] || errorMessages[ERROR_KEYS.UNKNOWN_ERROR];
};

export const getSuccessMessage = (successKey) => {
  const successMessages = {
    [SUCCESS_KEYS.REGISTRATION_SUCCESS]: "注册成功",
    [SUCCESS_KEYS.VERIFICATION_CODE_SENT]: "验证码已发送，请查收邮件",
    [SUCCESS_KEYS.LOGIN_SUCCESS]: "登录成功",
    [SUCCESS_KEYS.PASSWORD_RESET_SUCCESS]: "密码重置成功",
    [SUCCESS_KEYS.PASSWORD_RESET_EMAIL_SENT]: "密码重置邮件已发送，请查收",
    [SUCCESS_KEYS.EMAIL_VERIFICATION_SUCCESS]: "邮箱验证成功",
    [SUCCESS_KEYS.PROFILE_UPDATE_SUCCESS]: "个人信息更新成功",
    [SUCCESS_KEYS.OPERATION_SUCCESS]: "操作成功",
    [SUCCESS_KEYS.REGISTERING]: "注册中...",
    [SUCCESS_KEYS.LOGGING]: "登录中...",
    [SUCCESS_KEYS.COMPLETE_REGISTRATION]: "完成注册",
    [SUCCESS_KEYS.LOGOUT_SUCCESS]: "登出成功",
  };

  return successMessages[successKey] || "操作成功";
};
